spring:
  profiles:
    active:
    - dev
	
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: eureka-server7001  

eureka:
  instance:
    #hostname: localhost #eureka 服务端实例名 单机版用法 eureka ap(没有主节点,erekaserver节点角色都一样), zk cp
    hostname: com.cfg.eureka7001
  client:
    register-with-eureka: false # false表示不向eureka注册自己
    fetch-registry: false #false 表示自己就是注册中心,我的职责就是维护服务实例
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务 (单机版使用)
---
server:
  port: 7002 # yml,冒号后必须要有空格
spring:
  profiles: test
  application:
    name: eureka-server7002

eureka:
  instance:
    #hostname: localhost #eureka 服务端实例名 单机版用法 eureka ap(没有主节点,erekaserver节点角色都一样), zk cp
    hostname: com.cfg.eureka7002
  client:
    register-with-eureka: false # false表示不向eureka注册自己
    fetch-registry: false #false 表示自己就是注册中心,我的职责就是维护服务实例
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务 (单机版使用)