server:
  port: 8531
  servlet:
    context-path: /ssfda

spring:
  rabbitmq:
    addresses: localhost #10.10.66.53
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:  # 解决重复消费，启动多个实例一条消息每个实例都接收处理问题；通过添加组（-个组对应一个队列；不指定每个消费者一个队列；一个组中的服务只能有一个消费消息）
      bindings:
        myMessage: # 消息topic myMessage
          group: customer # 组名customer
    bus:
      ack:
        enabled: true
        destination-service: ssfda
      trace:
        enabled: true #开启消息跟踪
  application:
    name: ssfda
    # 引擎模板配置
  thymeleaf:
    cache: false # 关闭缓存
    mode: HTML5 # 去除htm5严格校验
    prefix: classpath:/templates/ # 指定 thymeleaf 模板路径
    encoding: UTF-8 # 指定字符集编码
  mvc:
    static-path-pattern: /static/** # js ,css 等静态文件路径

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8791/eureka/ #http://10.10.66.53:8761/eureka/
  instance:
    ip-address: 10.6.255.142

management:
  endpoints:
    web:
      exposure:
        include: "*"
